config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :pacsses do
    resources :comments
  end
  root 'pacsses#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :pacss
  validates :body, length: {minimum: 10 }
  after_save :update_pacss_time
  
  def update_pacss_time
    self.pacss.updated_at = Time.now
    self.pacss.save
  end
  
  def self.search(search)
    where("body LIKE ?", "%#{search}%")
  end
end

app/models/pacss.rb
class Pacss < ApplicationRecord
    validates :pacs_id, presence: true, length: { is: 12 }, uniqueness: true
    validates :ppmc, length: { maximum: 5 }
    validates :title, presence: true
    validates :owner, presence: true
    has_many :comments, dependent: :destroy
    has_many :stanjes
    
    def self.search(search)
        where("pacs_id LIKE ? OR title LIKE ? ", "%#{search}%", "%#{search}%")
    end

    def self.search_by_stat(search)
        if search == 'Samo_otvoreni'
            where("status NOT LIKE ?", "%Closed%") 
        else
            where("status LIKE ? or status LIKE ?", "%WithCustomer%", "%Pending Client Confirmation%")
        end
    end
end

app/models/stanje.rb
class Stanje < ApplicationRecord
  belongs_to :pacss
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
      !!current_user
  end
  
  def require_user
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_pacss
    
    def create
        @pacss.comments.create! comments_params
        redirect_to @pacss
    end
    
    private
        def set_pacss
            @pacss = Pacss.find(params[:pacss_id])
        end
        
        def comments_params
            params.required(:comment).permit(:body, :uneo)
        end
end

app/controllers/pacsses_controller.rb
class PacssesController < ApplicationController
  before_action :set_pacss, only: [:show, :edit, :update, :destroy]

  # GET /pacsses
  # GET /pacsses.json
  def index
    @pacsses = Pacss.all
    if params[:search]
      @pacsses_1 = @pacsses.search(params[:search])
      @pacsses.each do |pacss|
        pacss.comments.each do |comment|
          if comment.body.include?(params[:search])
            begin
              @pacsses_1 = @pacsses_1 + @pacsses.where(id: comment.pacss_id)
            rescue
              @pacsses_1 = @pacsses.where(id: comment.pacss_id)
            end
          end
				end
			end
			@pacsses = @pacsses_1.uniq
    elsif params[:status]
      @pacsses = @pacsses.search_by_stat(params[:status])
    elsif params[:by]
      @pacsses = Pacss.where(owner: params[:by])
    end
    begin
      @pacsses = @pacsses.order(:updated_at).reverse.uniq
    rescue
    end
  end

  # GET /pacsses/1
  # GET /pacsses/1.json
  def show
    # @pacsses = Pacss.all
  end

  # GET /pacsses/new
  def new
    @pacss = Pacss.new
  end

  # GET /pacsses/1/edit
  def edit
  end

  # POST /pacsses
  # POST /pacsses.json
  def create
    @pacss = Pacss.new(pacss_params)

    respond_to do |format|
      if @pacss.save
        @status = Stanje.new
        @status.pacss_id = @pacss.id
        @status.stanje = @pacss.status
        @status.save
        format.html { redirect_to @pacss, notice: 'Pacss was successfully created.' }
        format.json { render :show, status: :created, location: @pacss }
      else
        format.html { render :new }
        format.json { render json: @pacss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacsses/1
  # PATCH/PUT /pacsses/1.json
  def update
    respond_to do |format|
      if @pacss.update(pacss_params)
        @status = Stanje.new
        @status.pacss_id = @pacss.id
        @status.stanje = @pacss.status
        @status.save
        format.html { redirect_to @pacss, notice: 'Pacss was successfully updated.' }
        format.json { render :show, status: :ok, location: @pacss }
      else
        format.html { render :edit }
        format.json { render json: @pacss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacsses/1
  # DELETE /pacsses/1.json
  def destroy
    @pacss.destroy
    respond_to do |format|
      format.html { redirect_to pacsses_url, notice: 'Pacss was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pacss
      @pacss = Pacss.find(params[:id])
      @stanja = Stanje.where(pacss_id: params[:id]).order(created_at: :DESC)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pacss_params
      params.require(:pacss).permit(:pacs_id, :title, :owner, :ppmc, :status, :last_updated, :connected, :banka, :routines)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    redirect_to root_path
    
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
    else 
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pacsses_helper.rb
module PacssesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<pre id="comments"><%= comment.id %>: &nbsp;<%= comment.body %> -- <%= comment.created_at.to_s(:long) %><% if comment.uneo? %>&nbsp;[<%= comment.uneo %>]<% end %></pre>

app/views/comments/_new.html.erb
<%= form_for([ @pacss, Comment.new ], remote: true) do |form| %>
    <%= form.text_area :body, size: '50x10', autofocus: true %><br>
    <%= form.hidden_field :uneo, :value => current_user.username %>
    <%= form.submit "Sačuvaj", class: 'btn btn-dark' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
  </head>

  <body>
    <%= render 'pacsses/navbar'%>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/comments.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pacsses/_form.html.erb
<%= form_with(model: pacss, local: true) do |form| %>
  <% if pacss.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pacss.errors.count, "error") %> prohibited this pacss from being saved:</h2>

      <ul>
      <% pacss.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :pacs_id, id: :pacss_pacs_id, placeholder: "PACS ID", maxlength: "12" %>
  </div>
  
  <div class="field">
    <%= form.select :banka, options_for_select([['HGAA1'], ['HGAA2'], ['HGAA3'], ['HGAA4']], pacss.banka) %>
  </div>

  <div class="field">
    <%= form.text_field :title, id: :pacss_title, placeholder: "Naslov", size: pacss.title ?  pacss.title.length : "50" %>
  </div>

  <div class="field">
    <%= form.text_field :owner, id: :pacss_owner, placeholder: "Otvorio", size: pacss.owner ? pacss.owner.length : "50" %>
  </div>

  <div class="field">
    <%= form.text_field :ppmc, id: :pacss_ppmc, placeholder: "PPMC", maxlength: "5" %>
  </div>

  <div class="field">
    <%= form.select :status, options_for_select([['Closure reminder'], ['Pending Client Confirmation'], ['Closed'], ['New issue logged into RTC support system'], ['Open'], ['WithCustomer'], ['Maintenance']], pacss.status || ['New issue logged into RTC support system']) %>
  </div>
  
  <div class="field">
    <%= form.text_field :connected, id: :pacss_connected, placeholder: "Povezan sa..." %>
  </div>

  <div class="field">
    <%= form.text_field :routines, id: :pacss_routines, placeholder: "Rutine" %>
  </div>
  
  <div class="field">
    <%= form.date_select :last_updated, start_year: (pacss.created_at.blank? ? Time.now.year : pacss.created_at.year), end_year: Time.now.year, id: :pacss_last_updated %>
  </div>

  <div class="actions">
    <%= form.submit "Sačuvaj" %>
  </div>
<% end %>

app/views/pacsses/_last_5_comments.html.erb
<div style="float: right; border: 3px solid #ddd; border-radius: 10px; background-color: #a0a0a0; margin: 20px; max-width: 1200px; padding: 10px">

<% Comment.all.order(updated_at: :desc).first(5).each do |comm| %>
<div><%= link_to @pacsses.find(comm.pacss_id).pacs_id, @pacsses.find(comm.pacss_id) %><br><%= comm.updated_at.strftime("%d.%m---%H:%M") %></div>
<div class='comment'><%= comm.body[0..140] + '...' %></div>
<br><br>
<% end %>
</div>

app/views/pacsses/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "PAKSOVI", root_path, class: "navbar-brand" %>
  <% if logged_in? %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Novi PACS', new_pacss_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'PACSovi koji još nisu zatvoreni', root_path(status: 'Samo_otvoreni'), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'PACSovi koji čekaju DXC', root_path(status: 'DXC'), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Izloguj se', logout_path, method: :delete, class: "btn btn-outline-danger" %>
        </li>
      </ul>
  
        <%= form_tag(root_path, method: 'get', class: 'form-inline my-2 my-lg-0') do %>
          <%= search_field_tag :search, params[:search], class: "form-control mr-sm-2", type: "search", placeholder: "Pretraži PACSove" %>
          <%= submit_tag "Pretraži PACSove", :name => nil, class: "btn btn-success my-2 my-sm-0" %>
        <% end %>
      <% else %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'PACSovi koji još nisu zatvoreni', root_path(status: 'Samo_otvoreni'), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'PACSovi koji čekaju DXC', root_path(status: 'DXC'), class: "nav-link" %>
          </li>
        </ul>
        <%= form_for(:session, :html => { class: "form-inline my-2 my-lg-0 ml-auto", role: "form"}, url: login_path) do |f|%>
          <%= f.text_field :username, class: "form-control mr-sm-2", placeholder: "Ime"  %>
          <%= f.password_field :password, class: "form-control mr-sm-2", placeholder: "Šifra" %>
          <%= f.submit "Prijavi se", :name => nil, class: "btn btn-success my-2 my-sm-0" %>
        <% end %>
    </div>
  <% end %>
</nav>

app/views/pacsses/_pacss.html.erb
<div class="row mt-2 ml-5 mr-5 <%= pacss.status == 'Closed' ? 'Closed' : 'Open' %>">
    <div class="col-1"><%= pacss.banka %></div>
    <div class="col-1"><%= link_to pacss.pacs_id,pacss, class: pacss.status == 'Closed' ? '' : 'badge badge-pill badge-dark' %></div>
    <div class="col"><%= pacss.title %> (<%= pacss.comments.count - 1%>)</div>
    <div class="col-2"><%= pacss.owner.split(',')[1] %> <%= pacss.owner.split(',')[0] %></div>
    <div class="col-1"><%= pacss.status %></div>
    <div class="col-1"><%= time_ago_in_words(pacss.updated_at) %></div>
</div>
<div class="row mt-1 ml-5 mr-5">
    <div class="col-1"></div>
    <div class="col-1"></div>
    <div class="col">
        <% if params[:search] %>
            <% begin %>
                <% komentar = pacss.comments.search(params[:search]).last.body.gsub(/#{params[:search]}/i, '<mark>' + params[:search] + '</mark>') %>
                <%=raw komentar %>
            <% rescue %>
                <% begin %>
                    <%= pacss.comments.last.body %>
                <% rescue %>
                <% end %>
            <% end %>
        <% else %>
            <% if pacss.status != 'Closed' %>
            <% begin %>
                <%= pacss.comments.last.body[0...200] %><%= pacss.comments.last.body.length > 200 ? '...' : '' %>
            <% rescue %>
            <% end %>
            <% end %>
        <% end %>
</div>
<div class="col-2"></div>
<div class="col-1"></div>
<div class="col-1"></div>
</div>
<% if pacss.status != 'Closed' %>
<div class="row mt-1 ml-5 mr-5">
    <div class="col-1"></div>
    <div class="col-1"></div>
    <table>
      <tr style="height: 5em; border-top: 2px solid black; border-bottom: 2px solid black;">
        <% Stanje.where(pacss_id: pacss.id).order(:created_at).each do |s| %>
          <td style="<%= ['Open', 'New issue logged into RTC support system','Maintenance'].include?(s.stanje) ? 'vertical-align:bottom;' : (s.stanje != 'WithCustomer' ? 'vertical-align:top;color:green;' : 'color:red;') %>">
            <% if ['Open', 'New issue logged into RTC support system','Maintenance'].include?(s.stanje) %>
              &#10686;
            <% elsif s.stanje == 'WithCustomer' %>
              &#8226;
            <% else %>
              &#10687;
            <% end %>
            <br><%= s.created_at.strftime("%d.%m.") %>
          </td>
        <% end %>
      </tr>
    </table>
</div>
<% end %>
    <!--<% if pacss.status == "Closed" %>-->
    <!--    <tr class="Closed">-->
    <!--<% else %>-->
    <!--    <tr class="Open">-->
    <!--<% end %>-->
    <!--<td><%= pacss.banka %></td>-->
    <!--<td><%= link_to pacss.pacs_id,pacss %></td>-->
    <!--<td><%= pacss.title %> (<%= pacss.comments.count - 1%>)</td>-->
    <!--<td><%= pacss.owner %></td>-->
    <!--<td><%= pacss.status %></td>-->
    <!--<td><%= time_ago_in_words(pacss.updated_at) %></td>-->
    <!--</tr>-->
    <!--<tr>-->
    <!--<td></td><td></td>-->
    <!--<td class="comment">-->
    <!--<% if params[:search] %>-->
    <!--    <% begin %>-->
    <!--        <% komentar = pacss.comments.search(params[:search]).last.body.gsub(/#{params[:search]}/i, '<mark>' + params[:search] + '</mark>') %>-->
    <!--        <%=raw komentar %>-->
    <!--    <% rescue %>-->
    <!--        <% begin %>-->
    <!--            <%= pacss.comments.last.body %>-->
    <!--        <% rescue %>-->
    <!--        <% end %>-->
    <!--    <% end %>-->
    <!--<% else %>-->
    <!--    <% if pacss.status != 'Closed' %>-->
    <!--    <% begin %>-->
    <!--        <%= pacss.comments.last.body %>-->
    <!--    <% rescue %>-->
    <!--    <% end %>-->
    <!--    <% end %>-->
    <!--<% end %>-->
    <!--</td>-->
    <!--</tr>-->
    <!--<% if pacss.routines %>-->
    <!--    <% pacss.routines.split(",").each do |rutina| %>-->
    <!--    <tr>-->
    <!--    <td></td><td></td><td><span class="rutina"><%= rutina.strip %></span></td>-->
    <!--    </tr>-->
    <!--    <% end %>-->
    <!--<% end %>-->

app/views/pacsses/_stats.html.erb
<div class="pl-3 pr-3" style="width: 35em; margin-left: 5px;font-size: 12px; background-color: #333; color: #fff;">
  <% owners = Hash.new %>
  <% owners.default = 0 %>
  <% still_open = Hash.new %>
  <% still_open.default = 0 %>
  <% ukupno = 0 %>
  <% otvoreni = 0 %>
  <% Pacss.order(owner: :asc).each do |pacss| %>
    <% owners[pacss.owner] += 1 %>
    <% ukupno = ukupno+1 %>
    <% if pacss.status != 'Closed' %>
      <% still_open[pacss.owner] += 1 %>
      <% otvoreni = otvoreni + 1 %>
    <% end %>
  <% end %>

<br>
  
<% still_open.sort_by {|k,v| v}.reverse.each do |owner, tickets| %>
  <div class="owner_open">
    <%= link_to owner.to_s, root_path(:by => owner.to_s) %>
    <%= "_"*(40-owner.to_s.length) + tickets.to_s  + "/" + owners[owner].to_s %>
  </div>
<%end%>

<hr style="border: 1px solid white;">
<p class="owner text-right">Ukupno: <%= otvoreni %>/<%= ukupno %></p>
<hr style="border: 1px solid white;">
<div align="center" class="pb-2">
  <%= "HGAA1: " + Pacss.where(banka: "HGAA1").where.not(status: "Closed").count.to_s + "/" + Pacss.where(banka: "HGAA1").count.to_s + " | HGAA2: " + Pacss.where(banka: "HGAA2").where.not(status: "Closed").count.to_s + "/" + Pacss.where(banka: "HGAA2").count.to_s + " | HGAA3: " + Pacss.where(banka: "HGAA3").where.not(status: "Closed").count.to_s + "/" + Pacss.where(banka: "HGAA3").count.to_s + " | HGAA4: " + Pacss.where(banka: "HGAA4").where.not(status: "Closed").count.to_s + "/" + Pacss.where(banka: "HGAA4").count.to_s %>
</div>

</div>

app/views/pacsses/edit.html.erb
<% if logged_in? %>

<% provide :title, "Edit " + @pacss.pacs_id %>

<h1>Izmeni PACS</h1>

<%= render 'form', pacss: @pacss %>

<!--<%= link_to 'Show', @pacss %> |-->
<%= link_to 'Nazad', @pacss %>
<% end %>

app/views/pacsses/index.html.erb
<p id="notice"><%= notice %></p>

<br>

<% provide :title, "Paksovi"%>

<% if !params[:by] and !params[:search] %>
  <%= render 'stats' %>
<% end %>

<% #if logged_in? %>




  <div class="mt-3 ml-5 mr-5 row bg-dark text-white">
    <div class="col-1">Bank</div>
    <div class="col-1">PACS ID</div>
    <div class="col">Title</div>
    <div class="col-2">Owner</div>
    <div class="col-1">Status</div>
    <div class="col-1">Update</div>
  </div>

    <% if params[:search] %>
      <h1>&nbsp;&nbsp;&nbsp;&nbsp;<%= pluralize(@pacsses.uniq.count, 'result') %></h1>
    <% end %>
    <%= render partial: "pacss", collection: @pacsses %>



<% #end %>

app/views/pacsses/new.html.erb
<% if logged_in? %>

<% provide :title, "Novi PACS"%>

<h1>Novi PACS</h1>

<%= render 'form', pacss: @pacss %>

<%= link_to 'Početna', pacsses_path %>

<% end %>

app/views/pacsses/show.html.erb
<% #if logged_in? %>

<p id="notice"><%= notice %></p>

<% provide :title, @pacss.pacs_id %>

<p>
  <strong>PACS ID:</strong>
  <%= link_to @pacss.pacs_id, 'https://tcsp.temenos.com/SitePages/RedirectTicket.aspx?PACSID='+@pacss.pacs_id, class: 'badge badge-pill badge-dark p-1' %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @pacss.banka %>
</p>

<p>
  <strong>Title:</strong>
  <%= @pacss.title %>
</p>

<p>
  <strong>Owner:</strong>
  <% begin %>
  <% skype = 'sip:' + @pacss.owner.split(',')[1].strip.downcase + '.' + @pacss.owner.split(',')[0].strip.downcase + '@dxc.com' %>
  <%= link_to @pacss.owner, skype, class: 'badge badge-pill badge-dark p-1' %>
  <% rescue %>
  <%= @pacss.owner %>
  <% end %>
</div>
</p>

<p>
  <strong>Updated:</strong>
  <%= @pacss.last_updated.strftime("%d.%m.%Y") %>
</p>

<% if @pacss.connected != '' %>
  <p>
    <strong>Povezan sa:</strong>
    <% begin %>
    <%= link_to @pacss.connected, @pacsses.find_by(pacs_id:@pacss.connected).id.to_s, class: 'badge badge-pill badge-dark' %>
    <% rescue %>
    <% end %>
  </p>
<% end %>

<% if @pacss.routines != '' %>
  <p>
    <strong>Rutine:</strong>
    <% begin %>
    <%= @pacss.routines %>
    <% rescue %>
    <% end %>
  </p>
<% end %>

<p>
  <strong>Status:</strong>
  <%= @pacss.status %>
</p>

<%= link_to 'Izmeni', edit_pacss_path(@pacss), class: 'badge badge-pill badge-dark' %> |
<%= link_to 'Početna', root_path, class: 'badge badge-pill badge-dark' %>

<br><br>

<div class="p-2 mb-3" style="border:5px ridge black;width:fit-content;background-color:white;">
  <% @stanja.each do |s| %>
    <p>
      <span style="color:#fff;"><%= ['Open', 'New issue logged into RTC support system','Maintenance'].include?(s.stanje) ? '' : '---------- ' %></span>
      <%= s.created_at.strftime("%d.%m.") %> <%= s.stanje %>
    </p>
  <% end %>
</div>

<% if logged_in? %>
  <%= render 'comments/new', pacs: @pacss %>
<% end %>

  <% @pacss.comments.order(created_at: :desc).each do |komentar| %>
  <div>
    <%= render komentar %>
  </div>
  <% end %>

<% #end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest, id: :user_password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>